name: CI Build

on:
  push:
    branches: [devmaster]
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  pull_request:
    branches: [devmaster]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable sending .NET CLI telemetry

jobs:
  # MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore MAUIAction/MAUIAction/MAUIAction.csproj

      - name: Build MAUI Android
        run: dotnet publish MAUIAction/MAUIAction/MAUIAction.csproj -c Release -f net7.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: MAUIAction
          path: MAUIAction/MAUIAction/bin/Release/net7.0-android/*Signed.a*
      - name: Setup App Center CLI
        run: npm install -g appcenter-cli 
      - name: Setup App Center CLI
        run: appcenter apps list
      - name: Deploy to App Center
        run: appcenter distribute release --app Dev-Demo/MAUIAction
          --file MAUIAction/MAUIAction/bin/Release/net7.0-android/thes.maui.client-Signed.apk
          --token ${{ secrets.APP_CENTER_API_TOKEN_APP }} --group Owner

        # run: appcenter distribute release --silent --file MAUIAction/MAUIAction/MAUIAction.Android/bin/Release/thes.maui.client-Signed.apk --app DEV Demo/MAUIAction --group Collaborators --token ${{ secrets.APP_CENTER_API_TOKEN }}
        # env:
        #   API_TOKEN: ${{ secrets.APP_CENTER_API_TOKEN }}

      # MAUI Windows Build
      # build-windows:
      #   runs-on: windows-2022
      #   name: Windows Build
      #   steps:
      #     - name: Checkout
      #       uses: actions/checkout@v2

      #     - name: Setup .NET 7
      #       uses: actions/setup-dotnet@v1
      #       with:
      #         dotnet-version: 7.0.x
      #         include-prerelease: true

      #     - name: Setup MSBuild
      #       uses: microsoft/setup-msbuild@v1.1
      #       with:
      #         vs-prerelease: true

      #     - name: Install MAUI Workloads
      #       run: |
      #         dotnet workload install maui --ignore-failed-sources

      #     - name: Restore Dependencies
      #       run: dotnet restore MAUIAction/MAUIAction/MAUIAction.csproj

      #     - name: Build MAUI Windows
      #       run: msbuild MAUIAction/MAUIAction/MAUIAction.csproj -r -p:Configuration=Release -p:RestorePackages=false -p:TargetFramework=net7.0-windows10.0.19041 /p:GenerateAppxPackageOnBuild=true

      #     - name: Upload Windows Artifact
      #       uses: actions/upload-artifact@v2.3.1
      #       with:
      #         name: windows-ci-build
      #         path: MAUIAction/MAUIAction/bin/Release/net7.0-windows*/**/MAUIAction*.msix

      # MAUI iOS Build
      # build-ios:
      # runs-on: macos-13
      # name: iOS Build
      # steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore MAUIAction/MAUIAction/MAUIAction.csproj

      - name: Build MAUI iOS
        run: dotnet build MAUIAction/MAUIAction/MAUIAction.csproj -c Release -f net7.0-ios --no-restore

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ios-ci-build
          path: MAUIAction/MAUIAction/bin/Release/net7.0-ios/**/*.app/
# # MAUI MacCatalyst Build
# build-mac:
#   runs-on: macos-12
#   name: MacCatalyst Build
#   steps:

#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Setup .NET 7
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 7.0.x

#     - name: Install MAUI Workload
#       run: dotnet workload install maui --ignore-failed-sources

#     - name: Restore Dependencies
#       run: dotnet restore MAUIAction/MAUIAction/MAUIAction.csproj

#     - name: Build MAUI MacCatalyst
#       run: dotnet publish MAUIAction/MAUIAction/MAUIAction.csproj -c Release -f net7.0-maccatalyst --no-restore -p:BuildIpa=True

#     - name: Upload MacCatalyst Artifact
#       uses: actions/upload-artifact@v2.3.1
#       with:
#         name: mauibeach-macos-ci-build
#         path: MAUIAction/MAUIAction/bin/Release/net7.0-maccatalyst/maccatalyst-x64/publish/*.pkg
